# This file is a template, and might need editing before it works on your project.
# Full project:http://p2203403.pages.univ-lyon1.fr/my-beautiful-vue-app

image: busybox

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
      - public/mes-courses
      - public/ma-punition
      - public/mon-compteur
      - public/vacances
      - public/mon-blog
      - public/tactic-todo

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
